"""``EventRecord``: one finished event, checked and ready to store.

An ``EventRecord`` is immutable. When it is created, every field is checked
and cleaned up:

- Enum values become plain strings.
- Timestamps are converted to UTC. ``event_date`` is set from ``event_ts``.
- Counts become built-in ``int`` values. NumPy integers work too.
- ``metric_value`` becomes a built-in ``float``.

If a field is invalid, creating the record raises ``ValueError``. Metadata is
already JSON text (``metadata_json``) by the time it reaches this class. See
``metadata.py``.

To add a new field:

1. Add it to ``EventRecord`` below.
2. Add its name to the matching ``_..._FIELDS`` group so it gets checked.
3. Add its column to ``schema.py``.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, fields
from datetime import date, datetime, timezone
from enum import Enum
from numbers import Integral, Real
from typing import Any
from uuid import uuid4

from databricks_event_logger.context import RuntimeContext
from databricks_event_logger.enums import SEVERITY_VALUES, STATUS_VALUES
from databricks_event_logger.timing import utc_now
from databricks_event_logger.version import __version__

MAX_EVENT_NAME_CHARS = 255
MAX_EVENT_TYPE_CHARS = 100
MAX_INT64 = (1 << 63) - 1  # The largest value a BIGINT column can hold.

# Field groups. Each group is checked by the same rule in __post_init__.
_ENUM_FIELDS = ("event_name", "event_type", "status", "severity")
_REQUIRED_TEXT_FIELDS = (
    # (field name, maximum length or None)
    ("event_name", MAX_EVENT_NAME_CHARS),
    ("event_type", MAX_EVENT_TYPE_CHARS),
    ("event_id", None),
    ("sdk_version", None),
)
_OPTIONAL_TEXT_FIELDS = (
    "correlation_id", "parent_event_id", "app_name", "component", "environment",
    "source_table", "target_table", "metric_name", "error_class", "error_message",
    "stack_trace_hash", "error_frames_json", "metadata_json",
)
_TIMESTAMP_FIELDS = ("event_ts", "start_ts", "end_ts", "created_at")
_OPTIONAL_TIMESTAMP_FIELDS = ("start_ts", "end_ts")
_COUNT_FIELDS = ("row_count", "duration_ms")


@dataclass(frozen=True)
class EventRecord:
    """One event, checked and ready to deliver to a sink.

    You don't usually create these yourself. ``EventLogger`` creates them.
    Sinks receive them and call ``as_dict()`` or ``as_json_dict()``.

    Attributes:
        event_name: Nonblank string of at most 255 characters, for example
            ``"positions.validate"``. Text is not trimmed.
        event_type: A free-form category, such as ``"custom"``, ``"metric"``,
            ``"function"``, or ``"task"``. Nonblank, at most 100 characters.
        status: The outcome. See ``EventStatus``.
        event_id: Nonblank ID. A UUID is generated by default; caller-supplied
            IDs are not checked for uniqueness.
        correlation_id: Groups the events of one workflow or run.
        parent_event_id: The ``event_id`` of the scope this event ran inside.
        event_ts: Timezone-aware time when the event happened, converted to UTC.
        event_date: The UTC date of ``event_ts``, used to partition the table.
            It is always calculated for you.
        start_ts, end_ts: Optional timezone-aware times, converted to UTC.
            Their ordering is not checked.
        duration_ms: Optional integer from 0 through 2**63 - 1. Not calculated
            from start/end times by this class.
        severity: How important the event is. See ``EventSeverity``.
        app_name, component, environment: Who logged the event.
        sdk_version: Nonblank version text; defaults to this package's version.
        context: Where the code ran. See ``RuntimeContext``.
        source_table, target_table: The tables the operation read or wrote.
        row_count: Optional integer from 0 through 2**63 - 1. Never computed.
            Counts accept NumPy integers, but not bool or floats.
        metric_name: Optional metric label; not required with metric_value.
        metric_value: Optional finite real number, stored as float. Bool,
            NaN, infinity and values that overflow float are rejected.
        error_class, error_message, stack_trace_hash, error_frames_json:
            Filled in when the operation raised an exception.
        metadata_json: Optional text. The logger supplies sanitized JSON;
            this class checks its type, not its JSON syntax or contents.
        created_at: Timezone-aware creation time, converted to UTC.

    All optional text fields accept strings (including empty strings) or None.
    Names, types, status and severity also accept enums with suitable values.

    Raises:
        ValueError: A field fails the checks above, context is not a
            RuntimeContext, or status/severity is not an allowed value.
    """

    event_name: str
    event_type: str = "custom"
    status: str = "success"
    event_id: str = field(default_factory=lambda: str(uuid4()))
    correlation_id: str | None = None
    parent_event_id: str | None = None
    event_ts: datetime = field(default_factory=utc_now)
    event_date: date = field(init=False)
    start_ts: datetime | None = None
    end_ts: datetime | None = None
    duration_ms: int | None = None
    severity: str | None = None
    app_name: str | None = None
    component: str | None = None
    environment: str | None = None
    sdk_version: str = __version__
    context: RuntimeContext = field(default_factory=RuntimeContext)
    source_table: str | None = None
    target_table: str | None = None
    row_count: int | None = None
    metric_name: str | None = None
    metric_value: float | None = None
    error_class: str | None = None
    error_message: str | None = None
    stack_trace_hash: str | None = None
    error_frames_json: str | None = None
    metadata_json: str | None = None
    created_at: datetime = field(default_factory=utc_now)

    def __post_init__(self) -> None:
        """Check every field and store the cleaned-up values."""

        def store(name: str, value: Any) -> None:
            # The dataclass is frozen, so fields must be set this way.
            object.__setattr__(self, name, value)

        for name in _ENUM_FIELDS:
            value = getattr(self, name)
            if isinstance(value, Enum):
                store(name, value.value)

        for name, max_chars in _REQUIRED_TEXT_FIELDS:
            _check_required_text(name, getattr(self, name), max_chars)
        _check_choice("status", self.status, STATUS_VALUES)
        if self.severity is not None:
            _check_choice("severity", self.severity, SEVERITY_VALUES)
        for name in _OPTIONAL_TEXT_FIELDS:
            _check_optional_text(name, getattr(self, name))
        if not isinstance(self.context, RuntimeContext):
            raise ValueError("context must be a RuntimeContext.")

        # Order is part of validation: report the same first error as older releases.
        for name in _TIMESTAMP_FIELDS:
            value = getattr(self, name)
            if value is not None or name not in _OPTIONAL_TIMESTAMP_FIELDS:
                store(name, _to_utc(name, value))
        store("event_date", self.event_ts.date())

        for name in _COUNT_FIELDS:
            value = getattr(self, name)
            if value is not None:
                store(name, _to_count(name, value))
        if self.metric_value is not None:
            store("metric_value", _to_metric(self.metric_value))

    def as_dict(self) -> dict[str, Any]:
        """Return the event as one flat row, keyed by column name.

        Returns:
            A new dict. Context fields are placed at the top level, for example
            ``row["job_id"]``. Dates and timestamps stay as Python objects.
        """
        row = {item.name: getattr(self, item.name) for item in fields(self)}
        del row["context"]
        row.update(self.context.as_dict())
        return row

    def as_json_dict(self) -> dict[str, Any]:
        """Return ``as_dict()`` with dates and timestamps as ISO 8601 strings."""
        return {
            key: value.isoformat() if isinstance(value, datetime | date) else value
            for key, value in self.as_dict().items()
        }


def _check_required_text(name: str, value: Any, max_chars: int | None) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a non-empty string.")
    if max_chars is not None and len(value) > max_chars:
        raise ValueError(f"{name} must be {max_chars} characters or fewer.")


def _check_optional_text(name: str, value: Any) -> None:
    if value is not None and not isinstance(value, str):
        raise ValueError(f"{name} must be a string or None.")


def _check_choice(name: str, value: Any, choices: frozenset[str]) -> None:
    if not isinstance(value, str) or value not in choices:
        raise ValueError(f"{name} must be one of: {', '.join(sorted(choices))}.")


def _to_utc(name: str, value: Any) -> datetime:
    """Convert a timezone-aware datetime to UTC. Naive datetimes are rejected."""
    if not isinstance(value, datetime) or value.utcoffset() is None:
        raise ValueError(f"{name} must be a timezone-aware datetime.")
    return value.astimezone(timezone.utc)


def _to_count(name: str, value: Any) -> int:
    """Return ``value`` as an ``int`` that fits in a BIGINT column and is 0 or more.

    Any integer type is accepted, including NumPy integers. ``bool`` and
    floats are rejected, even ``7.0``.
    """
    message = f"{name} must be an integer from 0 through {MAX_INT64}."
    if isinstance(value, bool) or not isinstance(value, Integral):
        raise ValueError(message)
    value = int(value)
    if not 0 <= value <= MAX_INT64:
        raise ValueError(message)
    return value


def _to_metric(value: Any) -> float:
    """Return ``value`` as a finite ``float``.

    Any real number is accepted, including NumPy numbers. ``bool``, NaN,
    infinity, and numbers too large for a float are rejected.
    """
    message = "metric_value must be a finite number."
    if isinstance(value, bool) or not isinstance(value, Real):
        raise ValueError(message)
    try:
        number = float(value)
    except OverflowError as exc:
        raise ValueError(message) from exc
    if not math.isfinite(number):
        raise ValueError(message)
    return number
